# Generated by Django 4.2.1 on 2023-12-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletoverlap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('value', models.DecimalField(decimal_places=18, max_digits=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='tokens',
            field=models.ManyToManyField(related_name='wallets', to='walletoverlap.token'),
        ),
    ]
