# Generated by Django 4.2.1 on 2023-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletoverlap', '0002_ethereumtransaction_wallet_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AlterField(
            model_name='token',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
    ]
